export type Page =
  | 'Landing'
  | 'Login'
  | 'CreateAccount'
  | 'VerifyEmail'
  | 'ForgotPassword'
  | 'Onboarding'
  | 'Admin'
  | 'AI Ant'
  | 'Projects'
  | 'AI Teams'
  | 'Workflows'
  | 'Deliverables'
  | 'Approvals'
  | 'Knowledge'
  | 'Create Agent Team'
  | 'Templates'
  | 'Connectors'
  | 'Billing'
  | 'Settings';
