export type Page =
  | 'Landing'
  | 'Login'
  | 'CreateAccount'
  | 'VerifyEmail'
  | 'ForgotPassword'
  | 'Onboarding'
  | 'Admin'
  | 'AI Ant'
  | 'Bridge'
  | 'Projects'
  | 'AI Teams'
  | 'Workflows'
  | 'Deliverables'
  | 'Approvals'
  | 'Knowledge'
  | 'Create Agent Team'
  | 'Templates'
  | 'Connectors'
  | 'Billing'
  | 'Settings'
  | 'AccessPending'
  | 'MarketingProduct'
  | 'MarketingHowItWorks'
  | 'MarketingFeatures'
  | 'MarketingFeatureAIAnt'
  | 'MarketingFeatureColonyCrew'
  | 'MarketingFeatureOneManEnterprise'
  | 'MarketingFeatureAutomation'
  | 'MarketingFeatureColonyBridge'
  | 'MarketingPricing'
  | 'MarketingRoadmap'
  | 'MarketingAbout'
  | 'MarketingEarlyAccess'
  | 'MarketingPrivacy'
  | 'MarketingTerms';
