import type { Report, ReportSection, ReportSectionType, ReportTemplate, ScheduledReport } from '../types/appTypes';

export const REPORT_TEMPLATES: ReportTemplate[] = [
  { id: 'executive-summary', name: 'Executive Summary', description: 'High-level overview for leadership and stakeholders.', icon: '📋', defaultSections: ['summary', 'insights', 'metrics', 'recommendations'], supportsCharts: true, supportsTables: false, supportsTimeline: false },
  { id: 'detailed-analysis', name: 'Detailed Analysis', description: 'Full analysis with findings, data tables, and appendix.', icon: '🔍', defaultSections: ['summary', 'insights', 'findings', 'table', 'recommendations', 'appendix'], supportsCharts: true, supportsTables: true, supportsTimeline: true },
  { id: 'audit-report', name: 'Audit Report', description: 'Compliance and audit findings with risk levels.', icon: '🛡', defaultSections: ['summary', 'findings', 'table', 'recommendations', 'appendix', 'approval'], supportsCharts: false, supportsTables: true, supportsTimeline: true },
  { id: 'workflow-summary', name: 'Workflow Summary', description: 'Summary of a completed workflow run and its outputs.', icon: '⚡', defaultSections: ['summary', 'metrics', 'timeline', 'insights'], supportsCharts: true, supportsTables: false, supportsTimeline: true },
  { id: 'weekly-digest', name: 'Weekly Digest', description: 'Weekly performance digest for recurring review.', icon: '📅', defaultSections: ['summary', 'metrics', 'insights', 'recommendations'], supportsCharts: true, supportsTables: true, supportsTimeline: false },
  { id: 'incident-report', name: 'Incident Report', description: 'Structured incident documentation with root cause.', icon: '⚠', defaultSections: ['summary', 'findings', 'recommendations', 'timeline', 'appendix'], supportsCharts: false, supportsTables: false, supportsTimeline: true },
  { id: 'operational-review', name: 'Operational Review', description: 'Operations performance and process improvement recommendations.', icon: '⚙', defaultSections: ['summary', 'metrics', 'findings', 'recommendations', 'table'], supportsCharts: true, supportsTables: true, supportsTimeline: false },
  { id: 'blank', name: 'Blank Template', description: 'Start from scratch with empty sections.', icon: '📄', defaultSections: ['summary'], supportsCharts: false, supportsTables: false, supportsTimeline: false },
];

export const _mkSections = (types: ReportSectionType[], content: Partial<Record<ReportSectionType, string>> = {}): ReportSection[] =>
  types.map((t, i) => ({
    id: `sec-${t}`, type: t, enabled: true, order: i,
    title: t === 'summary' ? 'Summary' : t === 'insights' ? 'Key Insights' : t === 'metrics' ? 'Metrics' : t === 'findings' ? 'Findings' : t === 'recommendations' ? 'Recommendations' : t === 'table' ? 'Data Table' : t === 'timeline' ? 'Timeline' : t === 'appendix' ? 'Appendix' : 'Approval',
    content: content[t] ?? '',
  }));

export const MOCK_REPORTS: Report[] = [
  {
    id: 'rpt-001', workflowId: 'wf-1', runId: 'run-024',
    title: 'Workflow Compliance Review — May 14',
    template: 'audit-report', templateName: 'Audit Report',
    version: 3, currentVersionId: 'v3',
    status: 'Approved', approvalRequired: true, approvalStatus: 'Approved',
    createdAt: 'Today 09:13', updatedAt: 'Today 09:20',
    generatedBy: ['AI Scout', 'Analyst', 'Report Writer'], workflowName: 'Document Review Workflow',
    sections: _mkSections(['summary', 'findings', 'table', 'recommendations', 'appendix', 'approval'], {
      summary: 'This workflow compliance review identified 5 key findings across 42 processed records. Overall compliance rate is 88%, which is within acceptable parameters but requires attention in 3 areas.',
      findings: '1. Missing required fields in 4 records (customer_id).\n2. Data format inconsistencies in 7 entries.\n3. Duplicate entries found and resolved (3 total).\n4. Timestamp errors in batch uploaded records.\n5. Approval workflow correctly blocked external output.',
      recommendations: '• Update field validation rules to catch missing customer_id at intake.\n• Standardize date format enforcement across all input connectors.\n• Schedule weekly deduplication run.\n• Review batch upload parser for timestamp handling.',
    }),
    versions: [
      { id: 'v1', version: 1, editedBy: 'Report Writer', editedAt: 'Today 09:13', status: 'Draft', summary: 'Initial draft generated by workflow.', sections: [] },
      { id: 'v2', version: 2, editedBy: 'You', editedAt: 'Today 09:17', status: 'Edited', summary: 'Updated recommendations section with 4 action items.', sections: [] },
      { id: 'v3', version: 3, editedBy: 'You', editedAt: 'Today 09:20', status: 'Approved', summary: 'Approved and finalized for export.', sections: [] },
    ],
    exports: [
      { id: 'exp-1', format: 'pdf', exportedAt: 'Today 09:22', exportedBy: 'You' },
    ],
    tags: ['compliance', 'audit', 'approved'],
  },
  {
    id: 'rpt-002', workflowId: 'wf-1', runId: 'run-022',
    title: 'Operational Performance Digest — Week 19',
    template: 'weekly-digest', templateName: 'Weekly Digest',
    version: 1, currentVersionId: 'v1',
    status: 'Waiting Approval', approvalRequired: true, approvalStatus: 'Pending',
    createdAt: 'Yesterday 09:05', updatedAt: 'Yesterday 09:05',
    generatedBy: ['Analyst', 'Report Writer'], workflowName: 'Document Review Workflow',
    sections: _mkSections(['summary', 'metrics', 'insights', 'recommendations'], {
      summary: 'Week 19 performance digest covers 5 workflow runs with an 80% completion rate. Two workflows required manual intervention and one is pending approval.',
      insights: '• Workflow throughput increased 12% week-over-week.\n• Average run duration improved by 8 seconds.\n• 1 workflow is currently waiting for approval before proceeding.\n• Credit usage trending 15% below plan limit — healthy usage.',
      metrics: 'Total runs: 5 | Completed: 4 | Pending: 1 | Failed: 0 | Credits used this week: 24 / 300',
      recommendations: '• Approve pending workflow to unblock downstream tasks.\n• Review scheduling for off-peak runs to reduce latency.\n• Consider enabling auto-approval for low-risk workflows.',
    }),
    versions: [
      { id: 'v1', version: 1, editedBy: 'Report Writer', editedAt: 'Yesterday 09:05', status: 'Waiting Approval', summary: 'Auto-generated weekly digest.', sections: [] },
    ],
    exports: [],
    tags: ['weekly', 'operations', 'pending'],
  },
  {
    id: 'rpt-003', workflowId: 'wf-1', runId: 'run-021',
    title: 'Stakeholder Analysis Report — May 10',
    template: 'detailed-analysis', templateName: 'Detailed Analysis',
    version: 4, currentVersionId: 'v4',
    status: 'Final', approvalRequired: false, approvalStatus: 'None',
    createdAt: 'May 10 14:23', updatedAt: 'May 10 15:00',
    generatedBy: ['Analyst', 'Data Enricher', 'Report Writer', 'Email Sender'], workflowName: 'Document Review Workflow',
    sections: _mkSections(['summary', 'insights', 'findings', 'table', 'recommendations', 'appendix'], {
      summary: 'This analysis covers 85 records processed via webhook trigger. Full enrichment and analysis completed in 72 seconds. Report delivered to 8 stakeholders via email.',
      insights: '• 85 records analyzed with 98.8% data integrity.\n• 3 duplicates removed during normalization.\n• Webhook delivery latency: 42ms average.\n• 8 stakeholders notified successfully.',
      findings: 'Primary findings: high data quality, fast processing time, all enrichment fields populated correctly. Minor gap identified in webhook retry logic.',
      recommendations: '• Add webhook retry mechanism for failed delivery.\n• Consider archiving older records beyond 90 days.\n• Add dashboard widget for real-time throughput tracking.',
    }),
    versions: [
      { id: 'v1', version: 1, editedBy: 'Report Writer', editedAt: 'May 10 14:23', status: 'Draft', summary: 'Initial draft.', sections: [] },
      { id: 'v2', version: 2, editedBy: 'You', editedAt: 'May 10 14:35', status: 'Edited', summary: 'Added findings and enrichment notes.', sections: [] },
      { id: 'v3', version: 3, editedBy: 'You', editedAt: 'May 10 14:50', status: 'Edited', summary: 'Revised recommendations.', sections: [] },
      { id: 'v4', version: 4, editedBy: 'You', editedAt: 'May 10 15:00', status: 'Final', summary: 'Finalized and distributed.', sections: [] },
    ],
    exports: [
      { id: 'exp-2', format: 'pdf', exportedAt: 'May 10 15:01', exportedBy: 'You' },
      { id: 'exp-3', format: 'email', exportedAt: 'May 10 15:02', exportedBy: 'Email Sender' },
    ],
    tags: ['analysis', 'final', 'stakeholders'],
  },
  {
    id: 'rpt-004', workflowId: 'wf-1', runId: undefined,
    title: 'Incident Analysis — Data Cleaner Failure',
    template: 'incident-report', templateName: 'Incident Report',
    version: 1, currentVersionId: 'v1',
    status: 'Draft', approvalRequired: false, approvalStatus: 'None',
    createdAt: 'Today 08:45', updatedAt: 'Today 08:45',
    generatedBy: ['Analyst'], workflowName: 'Document Review Workflow',
    sections: _mkSections(['summary', 'findings', 'recommendations', 'timeline'], {
      summary: 'The Data Cleaner agent failed during Run #23 due to a missing required field (customer_id). The failure occurred 18 seconds into the run and halted downstream processing.',
      findings: 'Root cause: The uploaded CSV file was missing the "customer_id" column, which is required by the Data Cleaner\'s normalization logic. No fallback handling was in place.',
      recommendations: '• Add column validation step before Data Cleaner executes.\n• Implement graceful error recovery with user notification.\n• Add "required fields" list to workflow documentation.',
    }),
    versions: [
      { id: 'v1', version: 1, editedBy: 'Analyst', editedAt: 'Today 08:45', status: 'Draft', summary: 'Auto-generated incident report.', sections: [] },
    ],
    exports: [],
    tags: ['incident', 'draft', 'error'],
  },
];

export const MOCK_SCHEDULED_REPORTS: ScheduledReport[] = [
  {
    id: 'sch-001', workflowId: 'wf-1', workflowName: 'Document Review Workflow',
    title: 'Weekly Operational Digest', template: 'weekly-digest', templateName: 'Weekly Digest',
    frequency: 'weekly', time: '09:00', timezone: 'UTC+7',
    destination: 'email', destinationLabel: 'Email — team@company.com',
    recipients: 'team@company.com', channel: 'reports',
    approvalRequired: false, active: true,
    nextRun: 'Mon May 20 2026 09:00', lastRun: 'Mon May 13 2026 09:02',
    createdAt: 'May 1 2026',
  },
  {
    id: 'sch-002', workflowId: 'wf-1', workflowName: 'Document Review Workflow',
    title: 'Monthly Audit Summary', template: 'audit-report', templateName: 'Audit Report',
    frequency: 'monthly', time: '08:00', timezone: 'UTC+7',
    destination: 'approval-queue', destinationLabel: 'Approval Queue',
    recipients: '', channel: 'approvals',
    approvalRequired: true, active: true,
    nextRun: 'Jun 1 2026 08:00', lastRun: 'May 1 2026 08:05',
    createdAt: 'Jan 1 2026',
  },
];
